training:
  epochs: 100
  batch_size: 2
  save_path: "/home/anhkhoa/ViViT/saves"
  train_path : "/home/anhkhoa/spark_video_streaming/data/train"
  dev_path : "/home/anhkhoa/spark_video_streaming/data/val"
  test_path : "/home/anhkhoa/spark_video_streaming/data/test"
  reload: False
  logg : "/home/anhkhoa/ViViT/logs/r_tasa.log"
  result: "/home/anhkhoa/ViViT/result.txt"


optim:
  type: adam
  lr: 0.0001
  weight_decay: 0.0001
  decay_rate: 0.5

scheduler:
  lr_initial: 0.0001
  n_warmup_steps: 15000

model:
  num_classes: 6
  image_size: 224
  num_frames : 30
  patch_size: 16
  hidden_size: 768
  num_attention_heads: 12
  num_hidden_layers: 1
  intermediate_size: 3072
  model_name: "videomae"

# optim:
#   type: sgd
#   lr: 0.0001
#   momentum: 0.9
#   weight_decay: 0
#   begin_to_adjust_lr: 60
#   nesterov: None
#   decay_rate: 0.5

rnnt_loss:
  blank: 4
  reduction: "mean" 


